#!/bin/bash 

docker run \
-v "${PWD}/otel-local-config.yaml":/otel-local-config.yaml \
-p 4318:4318 \
otel/opentelemetry-collector \
--config otel-local-config.yaml;

# curl -i http://localhost:4318/v1/traces -X POST -H "Cont/json" -d @test-span.json
