#!/bin/bash 

docker run \
-v "${PWD}/otel-local-config.yaml":/otel-local-config.yaml \
-p 4318:4318 \
otel/opentelemetry-collector \
--config otel-local-config.yaml;

# to test it:
# curl -i http://localhost:4318/v1/traces -X POST -H "Content-Type: application/json" -d @test-span.json
